plugins {
	id 'fabric-loom' version '1.10.+'
	id 'maven-publish'
	id "com.modrinth.minotaur" version "2.+"
	id "com.github.breadmoirai.github-release" version "2.+"
	id "com.matthewprenger.cursegradle" version "1.+"
}

static String getBuildNo() {
	if (System.getenv().containsKey("GITHUB_RUN_NUMBER")) {
		return "+build." + System.getenv("GITHUB_RUN_NUMBER")
	} else {
		return "+dev"
	}
}

version = project.minecraft_version + "+" + project.mod_version + getBuildNo()
group = project.maven_group

System.out.println("Version: " + version)

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url = "https://maven.shedaniel.me/" }
	maven { url = "https://maven.terraformersmc.com/releases/" }
	maven { url = "https://maven.plutonia.xyz/maven" }
	maven { url = "https://maven.parchmentmc.org" }
	maven { url = "https://maven.quiltmc.org/repository/release" }
	maven { url = "https://api.modrinth.com/maven" } // Iris & Sodium
	maven { url = "https://repo.greenhouse.house/releases/" } // Farmer's Delight
	maven { url = "https://jitpack.io/" } // ASM (Farmer's Delight)
	maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes (Porting Lib)
	maven { url = "https://mvn.devos.one/releases/" } // Porting Lib (Farmer's Delight)

}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings(loom.layered {
		it.mappings "org.quiltmc:quilt-mappings:${minecraft_version}+build.${quilt_mappings}:intermediary-v2"
		it.officialMojangMappings { nameSyntheticMembers = false }
		it.parchment "org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip"
	})
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	modImplementation "ml.pluto7073:pdapi:${minecraft_version}+${pdapi_version}"

	modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
	modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${project.rei_version}"

	modImplementation "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"

	modRuntimeOnly "vectorwing:FarmersDelight:${minecraft_version}-${farmers_delight_version}+refabricated"
	modRuntimeOnly "ml.pluto7073:plutoscoffee:${minecraft_version}+${plutoscoffee_version}", { exclude module: "pdapi" }
	modRuntimeOnly "maven.modrinth:iris:${iris_version}"
	modRuntimeOnly "maven.modrinth:sodium:$sodium_version"
	modRuntimeOnly("org.antlr:antlr4-runtime:4.13.1")
	modRuntimeOnly("io.github.douira:glsl-transformer:2.0.1")
	modRuntimeOnly("org.anarres:jcpp:1.4.14")

	implementation(include("com.google.code.findbugs:jsr305:3.0.1"))
}

processResources {
	inputs.property "version", mod_version

	filesMatching("fabric.mod.json") {
		expand "version": mod_version
	}
}

tasks.register("buildOrPublish") {
	group = "build"
	String mavenUser = System.getenv("MAVEN_USER")
	if (mavenUser != null && !mavenUser.isEmpty()) {
		dependsOn(tasks.named("publish"))
		println("Prepared to publish")
	} else {
		dependsOn(tasks.named("build"))
		println("Prepared to build")
	}
}

loom {
	runs {
		configureEach {
			vmArg "-XX:+AllowEnhancedClassRedefinition"
			vmArg "-XX:+IgnoreUnrecognizedVMOptions"
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}

apply from: "gradle/publishing.gradle"
